# an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 5001

# Define environment variable
ENV FLASK_APP=product_service.py

# Run the application
CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]

